export const GET_DATA_REQUEST = "GET_DATA_REQUEST"
export const GET_DATA_FAIL =  "GET_DATA_FAIL"
export const GET_DELETEADVERTPIC_SUCCESS = "GET_DELETEADVERTPIC_SUCCESS"
export const GET_ADVERTPICLIST_SUCCESS = "GET_ADVERTPICLIST_SUCCESS"
